apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tom-frontend
rules:
- apiGroups: [""]
  resources: 
    - "endpoints"
  verbs: ["get", "list"]
  resourceNames: ["tom-backend"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tom-frontend
subjects:
- kind: ServiceAccount
  name: tom-frontend
roleRef:
  kind: Role 
  name: tom-frontend
  apiGroup: rbac.authorization.k8s.io