apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/jaberchez/kustomize-bases/project?ref=v1.1.2
  - ./tom-frontend
  
patches:
  - patch: |-
      - op: replace
        path: "/metadata/name"
        value: tom-dev  

      # Note: Important replace / for ~1 in annotation key
      - op: add
        path: "/metadata/annotations/openshift.io~1description"
        value: tom-dev

      - op: add
        path: "/metadata/annotations/openshift.io~1display-name"
        value: tom-dev

    target:
      kind: Project
      name: base-project
